In [1]:
import numpy as np
import pandas as pd

In [5]:
original_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])


print("Original NumPy Array:")
print(original_array)

new_array = original_array * 2

print("\nNew NumPy Array (elements multiplied by 2):")
print(new_array)

Original NumPy Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

New NumPy Array (elements multiplied by 2):
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [7]:
product_data = {
    'product_name': ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Webcam'],
    'price': [1200, 25, 75, 300, 50],
    'stock_quantity': [75, 120, 40, 60, 90]
}
products_df = pd.DataFrame(product_data)

print("\nOriginal Products DataFrame:")
print(products_df)



Original Products DataFrame:
  product_name  price  stock_quantity
0       Laptop   1200              75
1        Mouse     25             120
2     Keyboard     75              40
3      Monitor    300              60
4       Webcam     50              90


In [ ]:
high_stock_products = products_df[products_df['stock_quantity'] > 50]

print("\nProducts with Stock Quantity greater than 50:")
print(high_stock_products)




Products with Stock Quantity greater than 50:
  product_name  price  stock_quantity
0       Laptop   1200              75
1        Mouse     25             120
3      Monitor    300              60
4       Webcam     50              90
